In [1]:
import pandas as pd

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
data =pd.read_excel("iris-train.xlsx")

In [9]:
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [10]:
x=data.iloc[:,:-1]

In [11]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [13]:
y=data.iloc[:,-1]

In [14]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [15]:
model = RandomForestClassifier()

In [16]:
model.fit(x.values,y.values)

RandomForestClassifier()

In [26]:
prediction = model.predict([[5.4	,3	,4.5	,1.5]])

In [27]:
prediction

array(['Iris-versicolor'], dtype=object)

In [28]:
data_test = pd.read_excel("iris-test.xlsx")

In [29]:
data_test.head()

   sepallength  sepalwidth  petallength  petalwidth            class
0          5.4         3.0          4.5         1.5  Iris-versicolor
1          5.3         3.7          1.5         0.2      Iris-setosa
2          5.2         4.1          1.5         0.1      Iris-setosa
3          5.2         3.5          1.5         0.2      Iris-setosa
4          5.2         3.4          1.4         0.2      Iris-setosa

In [30]:
x_test = data_test.iloc[:,:-1]

In [31]:
x_test

    sepallength  sepalwidth  petallength  petalwidth
0           5.4         3.0          4.5         1.5
1           5.3         3.7          1.5         0.2
2           5.2         4.1          1.5         0.1
3           5.2         3.5          1.5         0.2
4           5.2         3.4          1.4         0.2
5           5.2         2.7          3.9         1.4
6           5.1         3.8          1.9         0.4
7           5.1         3.8          1.6         0.2
8           5.1         3.8          1.5         0.3
9           5.1         3.7          1.5         0.4
10          5.1         3.5          1.4         0.2
11          5.1         3.5          1.4         0.3
12          5.1         3.4          1.5         0.2
13          5.1         3.3          1.7         0.5
14          5.1         2.5          3.0         1.1
15          5.0         3.6          1.4         0.2
16          5.0         3.5          1.6         0.6
17          5.0         3.5          1.3         0.3
18          5.0         3.4          1.6         0.4
19          5.0         3.4          1.5         0.2
20          5.0         3.3          1.4         0.2
21          5.0         3.2          1.2         0.2
22          5.0         3.0          1.6         0.2
23          5.0         2.3          3.3         1.0
24          5.0         2.0          3.5         1.0
25          4.9         3.1          1.5         0.1
26          4.9         3.1          1.5         0.1
27          4.9         3.1          1.5         0.1
28          4.9         3.0          1.4         0.2
29          4.9         2.5          4.5         1.7
30          4.9         2.4          3.3         1.0
31          4.8         3.4          1.9         0.2
32          4.8         3.4          1.6         0.2
33          4.8         3.1          1.6         0.2

In [32]:
predictions=model.predict(x_test)

C:\Users\kando\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [33]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)